### ISSUE TITLE
inline math

### ISSUE THREAD

**Issue by abhayghatpande** [curiositry/mnml-ghost-theme#29]
Hi,

How to type inline math with the Katex?

One way I was typing math, was to use code injection (on Ghost Pro). In the head, I included the snippet:

```
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

Then, I could use (almost) standard MathJax syntax to include math: \\[ ... \\] or $$ ... $$ for display math and \\( ... \\) for inline math.

But if I apply mnml theme, the math elements get scroll bars around them. And I don't know how to modify the theme for Pro usage.

I have other questions about using the theme for Pro, such as how to create navigation, but will create a separate issue for that.

**Comment by curiositry** [comment]
Hey @abhayghatpande. Thanks for your question, and sorry for the delay. This issue is that Ghost parses anything in an inline element as markdown, and ignore the content of block level elements. That’s why I use sections for block level math — if I use an inline element, or even if I use a block level element *inline*, Ghost will parse the math as markdown before KaTeX can typeset it. 

I have asked (on the Ghost Slack chat) if there’s a way to get the Ghost markdown parser to ignore a particular inline HTML element and am awaiting a response. I’ll keep you posted!

**Comment by parrt** [comment]
Any movement on getting inline katex? thanks!

**Comment by curiositry** [comment]
@parrt Unfortunately, no :/

(But if you find a good solution, by all means submit a pull-request!)
