### ISSUE TITLE
Default Paragraph Spacing Too Small

### ISSUE THREAD

**Issue by alfiepates** [curiositry/mnml-ghost-theme#38]
I adore this theme but I think the default paragraph spacing is a little to small to make paragraphs separated enough for long blogposts not to feel like impenetrable walls of text. 

(For example, I just published [this blogpost](https://blog.alfiepates.me/2017/03/07/review-logitech-mx-anywhere-2/))

Again, I do think this theme is brilliant, it's by far my favourite out of all the themes I've taken a look at. Thanks for building it :) 

_(Additionally, I think titles/headers could do with some rework but I'll open a separate issue for that.)_

**Comment by curiositry** [comment]
@alfiepates Thanks.

MNML uses first-line indents (aka “traditional” or “print” style paragraphing) rather than space between paragraphs. This method is more traditional, but not as common as denoting the start of a new paragraph with a blank line (enough people ask “what are the crazy indents about?!” that I opted for the web-style when I built Laminim).

There isn’t an on-off switch, but it would be simple to change the CSS to use web style paragraphing if you like that style better.

You can read more about the two styles [here](http://practicaltypography.com/first-line-indents.html) and [here](http://practicaltypography.com/space-between-paragraphs.html).

**Comment by alfiepates** [comment]
Yeah, I'm aware of first-line indents, they're just not very well suited to reading text on raster displays with large fonts (IMO.) 

I think I shall fork MNML and maintain a version with "web" paragraphs... Or maybe I should just suck it up and buy Laminim ;)

**Comment by curiositry** [comment]
Nice!

You may want to remove the indent, now that there’s space between Also, I seem to recall I did some funky stuff with thumbnail positioning to make it work with the traditional paragraphing. It may not be a problem, but I’d test thumbnail alignment to make sure they look right. I put all the styles in a chunk, so you should be able to just comment out the whole block.

**Comment by alfiepates** [comment]
Yeah, this was more of a quick fix to make it readable ;) I'll do some proper CSS-tidying later on, but this will do For Now™
