### ISSUE TITLE
Markdown Header Rework Suggestions

### ISSUE THREAD

**Issue by alfiepates** [curiositry/mnml-ghost-theme#39]
The default top-level header size is _way_ too big. It's even bigger than the blogpost title! 

I think the entire set of header sizes could do with a bit of re-kerjiggering so that they flow slightly better with the body of the post, instead of being GIANT WORDS IN THE MIDDLE OF YOUR BLOGPOST, as they are currently. 

See [this post](https://blog.alfiepates.me/2017/03/07/review-logitech-mx-anywhere-2/) for an example.

**Comment by curiositry** [comment]
I see what you mean. The reason the first level headings are so large: MNML uses a type scale, and and making them some random less-enourmous size would mess up scale. Also, you’re not really supposed to *use* H1s inside a blog post, since it’s non semantic (technically the blog title (regardless of visual size) would be (pretty much the only) H1, the post title H2, and the section headers inside the post H3-H6s).

However, I realize that some people will be migrating existing content into MNML, or be used to using H1s inside posts, which may result in, as you pointed out, GIANT WORDS IN THE MIDDLE OF THEIR BLOGPOSTS.

I think the most elegant solutions would be to cap H1 and H2s in the post at the size of the H3 (maybe with some decoration to distinguish them), and leave typegreat for overrides for people who want giant words.

I take a whack at this as soon as I get a chance, and I’d also welcome a pull-request.

**Comment by alfiepates** [comment]
Thanks for the swift response :+1:
