### ISSUE TITLE
Paragraph margins on the post page are not visually the same as in the editor

### ISSUE THREAD

**Issue by lessless** [curiositry/mnml-ghost-theme#50]
Hi,

Paragraphs in the editor have a margin big enough to create a visual gap and thus visually separate blocks of text.

![parapgrahs in the editor](https://i.imgur.com/2uD00yH.png)

but on a post page, they're closely aligned to each other:

![paragraphs on the page](https://i.imgur.com/hPNXHuz.png)

I guess this is closer to what I will get by pressing "control+enter" in the editor, i.e. a "soft break", probably?

Would you think it makes sense to add a visual gap between paragraphs as in the editor?

Thank you for all the work!

**Comment by curiositry** [comment]
Hi @lessless. MNML uses traditional paragraphing by default:

 https://github.com/curiositry/mnml-ghost-theme/issues/38 

I have considered changing the default, since traditional paragraphing is less common these days, but haven't yet. I will probably add a toggle at some point, now that Ghost custom settings are released. In the meantime, see my reply to issue 38 if you would like to disable traditional paragraphing. 

Cheers!
