### ISSUE TITLE
Cannot get secondary navigation at the bottom of page to show up

### ISSUE THREAD

**Issue by horenmar** [curiositry/mnml-ghost-theme#56]
I am updating my blog from 2017 era mnml to current (and also from similarly old Ghost version to current), and ran into one issue.

I can't get the secondary navigation, at the bottom of the page, to show up. Initially I thought this is due to some editing error on my side, but it also does not show up for me using the version at current master. Instead, it only shows up if I change `partials/footer.hbs` to not include the navigation with `type="secondary"`.

Looking around in the commit history, I see that https://github.com/curiositry/mnml-ghost-theme/commit/022e3ec51fb7448dec34f103163e32be8e01e5b0 mentions that the `ifSecondary` helper is buggy; is this perhaps related?

**Comment by curiositry** [comment]
Odd, works fine on my machine with latest version of ghost + mnml. Since I use the exact markup to include the partial in my other themes, even with `  {{#if @site.secondary_navigation}}`, I would guess there's a bug somewhere in mnml's custom navigation helper. Have you tried deleting that file & reloading, to fall back on the default helper, and seeing if the nav shows up correctly?

**Comment by horenmar** [comment]
> Have you tried deleting that file & reloading, to fall back on the default helper, and seeing if the nav shows up correctly?

Do you mean deleting `partials/navigation.hbs` from the theme and uploading it like that?

**Comment by curiositry** [comment]
Correct.
